---
- name: Print Jenkins script directory
  debug:
    msg: "The Jenkins script directory is set to: {{ jenkins_script_dir }}"
  become: no
    
- name: Create Jenkins script directory
  file:
    path: "{{ jenkins_script_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: yes

- name: Create Jenkins data directory
  file:
    path: "{{ jenkins_home }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: yes

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Create Docker Compose file
  copy:
    content: |
      services:
        jenkins:
          image: jenkins/jenkins:lts-jdk17
          container_name: jenkins
          environment:
            - TZ=Asia/Seoul
          user: root
          privileged: true
          ports:
            - "{{ jenkins_port }}:8080"
            - "50000:50000"
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker
            - /usr/libexec/docker/:/usr/libexec/docker/
            - {{ jenkins_home }}:/var/jenkins_home
            - /usr/local/aws-cli:/usr/local/aws-cli
            - ~/.aws:/root/.aws
          restart: always
    dest: "{{ jenkins_script_dir }}/docker-compose.yml"
    
- name: Start Jenkins container
  command: docker-compose -f {{ jenkins_script_dir }}/docker-compose.yml up -d
  args:
    chdir: "{{ jenkins_script_dir }}"

- name: Get initial Jenkins password
  command: docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword
  register: jenkins_password
  changed_when: false

- name: Display Jenkins password
  debug:
    msg: "Initial Jenkins admin password: {{ jenkins_password.stdout }}"