- name: Firewall configurations
  block:
    - name: Check if firewalld is installed
      stat:
        path: /usr/bin/firewall-cmd
      register: firewalld_installed
      ignore_errors: yes

    - name: Check if ufw is installed
      stat:
        path: /usr/sbin/ufw
      register: ufw_installed
      ignore_errors: yes

    - name: Open ports for firewalld
      when: firewalld_installed.stat.exists
      block:
        - name: Open port 6443 for API Server
          shell: "firewall-cmd --add-port=6443/tcp --permanent"
          ignore_errors: yes

        - name: Open port 2379 for Etcd client communication
          shell: "firewall-cmd --add-port=2379/tcp --permanent"
          ignore_errors: yes

        - name: Open port 2380 for Etcd server-to-server communication
          shell: "firewall-cmd --add-port=2380/tcp --permanent"
          ignore_errors: yes

        - name: Open port 10250 for Kubelet
          shell: "firewall-cmd --add-port=10250/tcp --permanent"
          ignore_errors: yes
        
        - name: Reloading the firewalld
          shell: "firewall-cmd --reload"     
          ignore_errors: yes           

    - name: Open ports for ufw
      when: ufw_installed.stat.exists
      block:
        - name: Open port 6443 for API Server
          shell: "ufw allow 6443/tcp"
          ignore_errors: yes

        - name: Open port 2379 for Etcd client communication
          shell: "ufw allow 2379/tcp"
          ignore_errors: yes

        - name: Open port 2380 for Etcd server-to-server communication
          shell: "ufw allow 2380/tcp"
          ignore_errors: yes

        - name: Open port 10250 for Kubelet
          shell: "ufw allow 10250/tcp"
          ignore_errors: yes