# tasks/main.yml

- name: Create values.yaml for nginx-ingress
  template:
    src: values.yaml.j2
    dest: "./values.yaml"

- name: Add nginx-ingress helm repo
  command: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

- name: Update helm repo
  command: helm repo update
  register: repo_update
  changed_when: repo_update.rc == 0

- name: Install nginx-ingress using Helm
  command: >
    helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx 
    --namespace ingress-nginx --create-namespace 
    -f ./values.yaml

- name: Wait for ingress-nginx pods to be ready
  command: >
    kubectl wait --namespace ingress-nginx 
    --for=condition=ready pod 
    --selector=app.kubernetes.io/component=controller 
    --timeout=300s
  register: wait_pods
  changed_when: wait_pods.rc == 0

# 설치 상태 확인 작업들
- name: Check ingress-nginx namespace exists
  command: kubectl get namespace ingress-nginx
  register: namespace_check
  changed_when: false

- name: Check ingress-nginx pods status
  command: kubectl get pods -n ingress-nginx -l app.kubernetes.io/component=controller -o jsonpath='{.items[*].status.phase}'
  register: pods_status
  changed_when: false
  failed_when: "'Running' not in pods_status.stdout"

- name: Get ingress-nginx service
  command: kubectl get svc -n ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
  register: lb_hostname
  changed_when: false

- name: Check ingress-nginx service endpoints
  command: kubectl get endpoints -n ingress-nginx ingress-nginx-controller
  register: endpoints
  changed_when: false