# awscli 설치
- name: Check if AWS CLI is installed
  command: aws --version
  register: awscli_installed
  ignore_errors: yes

- name: Install AWS CLI if not installed
  import_tasks: awscli.yml
  when: awscli_installed.rc != 0

- name: Check if AWS Cloud Controller Manager is installed
  shell: |
    kubectl get daemonset aws-cloud-controller-manager -n kube-system --no-headers
  register: aws_cloud_controller_installed
  ignore_errors: yes

- name: Install AWS CLI if not installed
  import_tasks: aws_provider.yml
  when: aws_cloud_controller_installed.rc != 0

# NGINX Ingress Controller 설치 여부 확인 및 태스크 가져오기
# - name: Check if NGINX Ingress Controller is already installed
#   command: kubectl get deployment ingress-nginx-controller -n ingress-nginx
#   register: nginx_ingress_installed
#   ignore_errors: yes

# - import_tasks: nginx_ingress.yml
#   when: nginx_ingress_installed.rc != 0

# Argo CD 설치 여부 확인 및 태스크 가져오기
- name: Check if Argo CD is already installed
  command: kubectl get deployment argocd-server -n argocd
  register: argocd_installed
  ignore_errors: yes

- import_tasks: argocd.yml
  when: argocd_installed.rc != 0

# # Ingress 설치 여부 확인 및 태스크 가져오기
# - name: Check if Ingress is already installed
#   command: kubectl get ingress argocd-ingress -n argocd
#   register: ingress_installed
#   ignore_errors: yes

# - import_tasks: ingress.yml
#   when: ingress_installed.rc != 0

# git repo 연결하기
- import_tasks: gitrepo.yml