- name: Fetch join command from master node to worker nodes
  fetch:
    src: /tmp/join-command
    dest: /tmp/join-command
    flat: yes
  delegate_to: "{{ master_node }}"

- name: Copy join command to worker nodes
  copy:
    src: /tmp/join-command
    dest: /tmp/join-command
    mode: '0644'

- name: Execute join command on worker nodes
  shell: sh /tmp/join-command
  register: join_result
  retries: 3
  delay: 30
  until: join_result.rc == 0

- name: Clean up join command on worker nodes
  file:
    path: /tmp/join-command
    state: absent