- name: Download Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0700'

- name: Install Helm
  command: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm

- name: Check if Helm is installed
  command: helm version --short
  register: helm_version
  changed_when: false

- name: Display Helm installation status
  debug:
    msg: "Helm is {{ 'installed' if helm_version.rc == 0 else 'not installed' }}"

- name: Clean up install script
  file:
    path: /tmp/get_helm.sh
    state: absent