# # ansible-galaxy collection install ansible.posix kubernetes.core

# - hosts: dev_master
#   vars:
#     kubernetes_version: "1.30"
#     pod_network_cidr: "192.168.0.0/16"
#     api_server_address: "{{ ansible_default_ipv4.address }}"
#   become: yes
#   roles:
#    - k8s/common
#    - k8s/master

# - name: Setup Calico and ArgoCD
#   hosts: dev_master
#   become: yes
#   vars:
#     calico_version: "3.28.1"
#   roles:
#    - k8s/network
#    - k8s/helm

# - hosts: dev_workers
#   vars:
#     kubernetes_version: "1.30"
#     master_node : "dev-master-1"
#   become: yes
#   roles:
#   - k8s/common
#   - k8s/worker

---
- name: Update hostnames and collect information
  hosts: dev
  become: yes
  gather_facts: yes
  roles:
    - k8s/host