---
- name: Update hostnames and manage /etc/hosts
  hosts: dev
  become: yes
  gather_facts: yes

  tasks:
    - name: Set hostname using hostnamectl
      command: hostnamectl set-hostname {{ inventory_hostname }} --static
      become: yes

    - name: Ensure new hostname is in /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: '127.0.1.1 {{ inventory_hostname }}'

    - name: Get internal IP address
      set_fact:
        internal_ip: "{{ ansible_default_ipv4.address }}"

    - name: Collect host information and delegate to localhost
      set_fact:
        host_info: "{{ hostvars['localhost']['host_info'] | default([]) + [{'name': inventory_hostname, 'ip': internal_ip}] }}"
      delegate_to: localhost
      delegate_facts: true
      when: hostvars['localhost']['host_info'] is defined

    - name: Initialize host_info on localhost if not defined
      set_fact:
        host_info: []
      delegate_to: localhost
      delegate_facts: true
      when: hostvars['localhost']['host_info'] is not defined

- name: Create hosts.ini file locally
  hosts: localhost
  connection: local
  become: no

  tasks:
    - name: Create hosts.ini file with collected information
      copy:
        content: "{% for host in host_info %}{{ host.name }} {{ host.ip }}\n{% endfor %}"
        dest: "./hosts.ini"

    - name: Display hosts.ini content
      debug:
        msg: "hosts.ini content:\n{{ lookup('file', './hosts.ini') }}"

# - name: Update /etc/hosts on all servers
#   hosts: dev
#   become: yes

#   tasks:
#     - name: Backup existing /etc/hosts file
#       copy:
#         src: /etc/hosts
#         dest: /etc/hosts.backup_{{ ansible_date_time.iso8601 }}
#         backup: yes
#       register: backup_result

#     - name: Show backup file location
#       debug:
#         msg: "Backup created at: {{ backup_result.dest }}"

#     - name: Add entries to /etc/hosts from hosts.ini
#       blockinfile:
#         path: /etc/hosts
#         block: "{{ lookup('file', './hosts.ini') }}"
#         marker: "# {mark} ANSIBLE MANAGED BLOCK - DEV HOSTS"
