- name: Setup ArgoCD SSH Authentication with GitHub
  hosts: kube_control_plane
  become: true
  vars:
    service_port: 30080
    git_repo_url: "https://github.com/your-username/infrastructure-gitops.git"
    git_username: "suugit"
    git_token: "ghp"
  roles:
    - db