---
- name: Remove AWS Load Balancer Webhook configurations
  command: "{{ item }}"
  loop:
    - "kubectl delete validatingwebhookconfiguration aws-load-balancer-webhook --ignore-not-found=true"
    - "kubectl delete mutatingwebhookconfiguration aws-load-balancer-webhook --ignore-not-found=true"
  ignore_errors: yes
  register: webhook_delete
  changed_when: "'deleted' in webhook_delete.stderr or 'deleted' in webhook_delete.stdout"

- name: Remove Cert Manager Webhook configurations
  command: "{{ item }}"
  loop:
    - "kubectl delete validatingwebhookconfiguration cert-manager-webhook --ignore-not-found=true"
    - "kubectl delete mutatingwebhookconfiguration cert-manager-webhook --ignore-not-found=true"
  ignore_errors: yes
  register: cert_webhook_delete
  changed_when: "'deleted' in cert_webhook_delete.stderr or 'deleted' in cert_webhook_delete.stdout"

- name: Remove Cert Manager resources
  command: kubectl delete -f https://github.com/cert-manager/cert-manager/releases/download/v1.16.0/cert-manager.yaml --ignore-not-found=true
  ignore_errors: yes
  register: cert_manager_delete
  changed_when: "'deleted' in cert_manager_delete.stderr or 'deleted' in cert_manager_delete.stdout"

- name: Force delete cert-manager namespace if still exists
  command: kubectl delete namespace cert-manager --force --grace-period=0 --ignore-not-found=true
  ignore_errors: yes
  register: namespace_delete
  changed_when: "'deleted' in namespace_delete.stderr or 'deleted' in namespace_delete.stdout"

- name: Remove Cert Manager CRDs
  command: "kubectl delete crd {{ item }} --ignore-not-found=true"
  loop:
    - certificaterequests.cert-manager.io
    - certificates.cert-manager.io
    - challenges.acme.cert-manager.io
    - clusterissuers.cert-manager.io
    - issuers.cert-manager.io
    - orders.acme.cert-manager.io
  ignore_errors: yes
  register: crd_delete
  changed_when: "'deleted' in crd_delete.stderr or 'deleted' in crd_delete.stdout"


- name: Remove serviceaccount
  command: helm uninstall aws-load-balancer-controller -n kube-system
  ignore_errors: yes
  
- name: Delete AWS Load Balancer Controller deployment
  command: kubectl delete deployment aws-load-balancer-controller -n kube-system
  ignore_errors: yes

- name: Delete AWS Load Balancer Controller service
  command: kubectl delete service aws-load-balancer-webhook-service -n kube-system
  ignore_errors: yes


- name: Remove EKS Helm repository
  command: helm repo remove eks
  ignore_errors: yes

- name: Remove serviceaccount
  command: kubectl delete serviceaccount aws-load-balancer-controller -n kube-system
  ignore_errors: yes

