
# 테라폼 설정 확인필요: 서브넷 쿠버네티스 태그 / ec2 쿠버네티스 태그 / ec2 iam권한(EKS는 여기서 생성함 보통)
- name: Add EKS Helm repository
  command: helm repo add eks https://aws.github.io/eks-charts

- name: Update Helm repositories
  command: helm repo update
- name: Check existing ACM certificates
  command: aws acm list-certificates --region ap-northeast-2
  register: acm_result

- name: Create ACM certificate if not exists
  command: >
   aws acm request-certificate 
   --region ap-northeast-2
   --domain-name "{{ domain_name }}"
   --validation-method DNS
   --subject-alternative-names "*.{{ domain_name }}"
  when: domain_name not in acm_result.stdout
  register: new_cert

- name: Get certificate ARN
  command: >
   aws acm describe-certificate 
   --region ap-northeast-2
   --certificate-arn "{{ new_cert.stdout | from_json | json_query('CertificateArn') }}"
  when: new_cert.changed
  register: cert_details

- name: Store certificate ARN
  set_fact:
   cert_arn: "{{ cert_details.stdout | from_json | json_query('Certificate.CertificateArn') }}"
  when: new_cert.changed

# 이후 AWS Load Balancer Controller 설치 시 cert_arn 변수 사용
- name: Install AWS Load Balancer Controller
  command: >
   helm install aws-load-balancer-controller eks/aws-load-balancer-controller 
   -n kube-system 
   --set clusterName={{ cluster_name }} 
   --set serviceAccount.create=true 
   --set serviceAccount.name=aws-load-balancer-controller 
   --set region=ap-northeast-2 
   --set vpcId={{ vpc_id }}
   --set defaultTags.acm-certificate-arn={{ cert_arn }}
   --set enableServiceMutatorWebhook=false

# kubectl delete -n kube-system deployment aws-load-balancer-webhook
# kubectl delete -n kube-system service aws-load-balancer-webhook-service

- name: Wait for AWS Load Balancer Controller to be ready
  command: kubectl rollout status deployment/aws-load-balancer-controller -n kube-system
  register: rollout_status
  until: rollout_status.rc == 0
  retries: 30
  delay: 10

- name: Verify AWS Load Balancer Controller installation
  command: kubectl get deployment -n kube-system aws-load-balancer-controller
  register: verify_result