- name: Create Argo CD namespace
  command: "kubectl create namespace argocd"
  ignore_errors: yes

- name: Create ingress-nginx namespace
  command: "kubectl create namespace ingress-nginx"
  ignore_errors: yes

- name: Add Helm repository for Argo CD
  command: "helm repo add argo https://argoproj.github.io/argo-helm"

- name: Add Helm repository for Nginx Ingress
  command: "helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx"

- name: Update Helm repositories
  command: "helm repo update"

- name: Remove existing manifests directory if it exists
  file:
    path: /tmp/manifests
    state: absent

- name: Clone manifest repository using credentials via shell
  shell: "git clone https://{{ git_username }}:{{ git_token }}@github.com/Parrotalk/Parrotalk-Manifests.git /tmp/manifests --branch main"
  no_log: true

- name: Install Argo CD using Helm
  command: >
    helm upgrade --install argocd argo/argo-cd --namespace argocd 
    --values /tmp/manifests/argocd/{{ env }}/values.yaml

- name: Install or Upgrade Nginx Ingress Controller using Helm
  command: >
    helm upgrade --install nginx-ingress ingress-nginx/ingress-nginx --namespace ingress-nginx

- name: Apply ArgoCD Ingress
  command: >
    kubectl apply -f /tmp/manifests/argocd/{{ env }}/ingress.yaml

- name: Wait for Argo CD pods to be ready
  command: >
    kubectl wait --for=condition=Ready pod -l app.kubernetes.io/name=argocd-server -n argocd --timeout=300s

# - name: Cleanup cloned repository
#   command: "rm -rf /tmp/manifests"
