- name: Download Calico v3.28.1 manifest
  get_url:
    url: "https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/calico.yaml"
    dest: /etc/kubernetes/calico-{{ calico_version }}.yaml
    mode: '0644'

- name: Apply Calico v3.28.1 manifest
  command: kubectl apply -f /etc/kubernetes/calico-{{ calico_version }}.yaml
  register: apply_result
  changed_when: "'configured' in apply_result.stdout or 'created' in apply_result.stdout"
  failed_when: 
    - apply_result.rc != 0
    - "'AlreadyExists' not in apply_result.stderr"

- name: Wait for Calico pods to be ready
  command: kubectl wait --for=condition=ready pods -l k8s-app=calico-node -n kube-system --timeout=300s
  register: wait_result
  retries: 5
  delay: 10
  until: wait_result.rc == 0

- name: Verify Calico installation
  command: kubectl get pods -n kube-system -l k8s-app=calico-node
  register: calico_pods
  changed_when: false

- name: Display Calico pod status
  debug:
    var: calico_pods.stdout_lines