---
- name: Kubernetes pre-flight checks
  block:
    - name: Check if containerd is installed
      command: which containerd
      register: containerd_check
      ignore_errors: yes

    - name: Check containerd version
      command: containerd --version
      register: containerd_version
      when: containerd_check.rc == 0

    - name: Verify containerd config
      command: cat /etc/containerd/config.toml
      register: containerd_config
      when: containerd_check.rc == 0

    - name: Check if kubelet is installed
      command: which kubelet
      register: kubelet_check
      ignore_errors: yes

    - name: Check kubelet version
      command: kubelet --version
      register: kubelet_version
      when: kubelet_check.rc == 0

    - name: Check if kubeadm is installed
      command: which kubeadm
      register: kubeadm_check
      ignore_errors: yes

    - name: Check kubeadm version
      command: kubeadm version
      register: kubeadm_version
      when: kubeadm_check.rc == 0

    - name: Check if socat is installed
      command: which socat
      register: socat_check
      ignore_errors: yes

    - name: Verify system requirements
      assert:
        that:
          - containerd_check.rc == 0
          - kubelet_check.rc == 0
          - kubeadm_check.rc == 0
          - socat_check.rc == 0
          - "'SystemdCgroup = true' in containerd_config.stdout"
        fail_msg: "One or more system requirements are not met. Please check the output."
        success_msg: "All system requirements are met."

    - name: Display versions
      debug:
        msg:
          - "Containerd version: {{ containerd_version.stdout | default('Not installed') }}"
          - "Kubelet version: {{ kubelet_version.stdout | default('Not installed') }}"
          - "Kubeadm version: {{ kubeadm_version.stdout | default('Not installed') }}"

  rescue:
    - name: Display error message
      debug:
        msg: "Pre-flight checks failed. Please review the output and address any missing requirements."

    - name: Fail the play
      fail:
        msg: "Aborting due to failed pre-flight checks."