- name: Reset kubeadm cluster
  become: yes
  block:
    - name: Drain nodes
      kubectl:
        command: drain
        node: "{{ item }}"
        delete_emptydir_data: true
        force: true
        ignore_daemonsets: true
      with_items: "{{ groups.nodes }}"
      ignore_errors: yes
      when: "'controlplane' in group_names"

    - name: Reset kubeadm on nodes
      command: kubeadm reset -f
      when: "'nodes' in group_names"

    - name: Reset iptables rules
      ansible.builtin.iptables:
        table: "{{ item }}"
        chain: ALL
        flush: true
      with_items:
        - filter
        - nat
        - mangle

    - name: Delete nodes from Kubernetes
      kubectl:
        command: delete
        kind: node
        name: "{{ item }}"
      with_items: "{{ groups.nodes }}"
      ignore_errors: yes
      when: "'controlplane' in group_names"

    - name: Reset kubeadm on control plane
      command: kubeadm reset -f
      when: "'controlplane' in group_names"

  when:
    - kubeadm_reset is defined
    - kubeadm_reset
  tags:
    - kubernetes/kubeadm/reset
